### ISSUE TITLE
install.sh mode

### ISSUE THREAD

**Issue by grahamperrin** [RoboChimera/ChimeraCord#2]
https://github.com/RoboChimera/ChimeraCord/commit/00ef48b148b45689245a9cbfe22e7092df49d0ce#diff-01e6d9ffed056a02cae8d8a0ec5d476a64d017bf85c0d5a94bb23ca21f33f5aaR8

Is it still necessary to change the mode? 

Today, after removal then a `git pull`, I found it readily executable: 

```text
% pwd
/usr/home/grahamperrin/dev/ChimeraCord
% ls -hl install.sh 
-rwxr-xr-x  1 grahamperrin  grahamperrin   832B  5 Sep 00:49 install.sh
% 
```

**Comment by RoboChimera** [comment]
If it is already executable then I guess not.
